on: pull_request

jobs:
  first:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        is_hybrid: [true, false]
    outputs:
      IS_HYBRID: ${{ steps.check.outputs.IS_HYBRID }}
    steps:
      - id: check
        run: echo "IS_HYBRID=${{ matrix.is_hybrid }}" >> "$GITHUB_OUTPUT"

  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Check dependent value
        run: echo "${{ needs.first.outputs.IS_HYBRID }}"
