on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ 'false' == 'true' }}
        id: skippedStep
        run: echo "SKIPPED=true" >> "$GITHUB_OUTPUT"

      - run: |
          if [[ ${{ steps.skippedStep.outputs.SKIPPED && 'true' || 'false' }} == 'true' ]]; then
            echo "whoa"
          else
            echo "That's expected"
          fi
