name: Update E/App reference to Mobile-Expensify

on:
  push:

jobs:
  updateEApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Expensify/App
          token: ${{ secrets.OS_BOTIFY_TOKEN }}
          # We don't actually need the whole repo, just the Mobile-Expensify submodule
          sparse-checkout: Mobile-Expensify
          submodules: true

      - uses: Expensify/GitHub-Actions/actions/setupGitForOSBotify@main
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OS_BOTIFY_APP_ID: ${{ secrets.OS_BOTIFY_APP_ID }}
          SETUP_AS_APP: false
