name: Test push compare
on:
  push:
    branches: [Rory-TestPushCompare]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Going to add amend
      - run: echo '${{ toJSON(github.event.commits) }}'
