name: Test push compare
on:
  push:
    branches: [Rory-TestPushCompare]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Going to add amend
      - uses: actions/github-script@e7aeb8c663f696059ebb5f9ab1425ed2ef511bdb
        with:
          script: |
            const commits = JSON.parse(context.payload.commits);
            console.log(commits);
