name: Verify Podfile

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths:
      - ios/**
      - "package.json"
      - "package-lock.json"

jobs:
  verify:
    if: github.actor != 'OSBotify' && github.actor != 'imgbot[bot]'
    runs-on: macos-latest
    steps:
      - name: Checkout
        # v4
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode

      - name: Verify podfile
        run: ./.github/scripts/verifyPodfile.sh
